
logging:
  level:
    root: INFO
    org.springframework.cloud.config: INFO

server:
  port: 8082

VAULT_HOST: http://localhost:8200
VAULT_ROLE_ID: ea0de26c-2aa2-e218-920a-5ef4fd883bdf
VAULT_SECRET_ID: 0bb0f2cc-e97a-cfab-d708-cb38a00e25b4
vault-engine: secret

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: vault
  application.name: gateway

#  cloud.config.server:
#    vault:
#      host: localhost
#      port: 8200
#      scheme: http
#      kv-version: 2
#      authentication: APPROLE
#      app-role:
#        app-role-path: secret/gateway/dev
#        role: configserver
#        role-id: ea0de26c-2aa2-e218-920a-5ef4fd883bdf
#        secret-id: 0bb0f2cc-e97a-cfab-d708-cb38a00e25b4


  data:
    mongodb:
      uri: mongodb://localhost/manman