

server:
  port: 8082


spring:
  profiles:
    active: vault
  application.name: gateway

  cloud.config.server:
    vault:
      host: localhost
      port: 8200
      scheme: http
      kv-version: 2
      authentication: TOKEN
      token: hvs.NtkFozm8Zffl8TBQVQ206dUp

  data:
    mongodb:
      uri: mongodb://localhost/manman